version: "3.7"

services:
  backend:
    container_name: nest_backend
    restart: always
    build: .
    environment:
      - APP_ENV=development
      - APP_PORT=5000
    volumes:
      - ./src:/var/www/nest_backend/src
      - ./test:/var/www/nest_backend/test
    working_dir: /var/www/nest_backend
    ports:
      - "5000:5000"
    links:
      - mysql
      - redis
    depends_on:
      - mysql
      - redis
  mysql: # Example Service
    container_name: nest_mysql
    restart: always
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=nest_user
      - MYSQL_PASSWORD=nestuser
      - MYSQL_DATABASE=nest_docker_test
    ports:
    - "3969:3306"
    volumes:
    - nest_mysql_data:/var/lib/mysql

  dbadmin:
    container_name: nest_phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    links:
     - mysql:mysql
    depends_on:
     - mysql
    ports:
     - "8080:80"
    environment:
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: mysql
      PMA_PORT: 3306

  redis: # Example Service
    container_name: nest_redis
    restart: always
    image: redis:6.0-alpine
    expose:
      - "6379"
    volumes:
      - nest_redis_data:/data

volumes:
  nest_mysql_data:
  nest_redis_data:

networks:
  default:
    external:
      name: nest